my_project/my_app/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers
app_name = "employees"


router = routers.DefaultRouter()
router.register('employees', views.EmployeeView)
# router.register('job_type', views.TypeView)
# router.register('kind', views.KindView)
# router.register('specified', views.SpecifiedView)


urlpatterns = [
    path('api/', include(router.urls)),
    path('employees/', views.employees_list, name='data'),
    path('<slug:slug>', views.employee_details, name='details')

]

my_project/my_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from my_app import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('my_app/', include('my_app.urls')),
    path('', views.employees_list, name='home'),
    path('api_auth', include('rest_framework.urls'))

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_project/my_app/models.py
from django.db import models


class Employee(models.Model):
    employee_id = models.IntegerField(blank=True, null=True)
    first_name = models.CharField(max_length=100, blank=True, null=True)
    last_name = models.CharField(max_length=100, blank=True, null=True)
    email = models.CharField(max_length=100, blank=True, null=True)
    phone_number = models.CharField(max_length=100, blank=True, null=True)
    hire_date = models.DateField(blank=True, null=True)
    job_id = models.CharField(max_length=200, blank=True, null=True)
    salary = models.IntegerField(blank=True, null=True)
    manager_id = models.IntegerField(blank=True, null=True)
    department_id = models.IntegerField(blank=True, null=True)
    thumb = models.ImageField(default='default.png', blank=True)
    general = models.TextField(null=True)
    slug = models.SlugField(blank=True, null=True)

    def __str__(self):
        return self.first_name

my_project/my_app/views.py
from django.shortcuts import render
from .models import Employee
from .serializers import EmployeeSerializer
from rest_framework import viewsets, permissions


class EmployeeView(viewsets.ModelViewSet):
    queryset = Employee.objects.all()
    serializer_class = EmployeeSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)


def employees_list(request):
    employees = Employee.objects.all()
    return render(request, 'employees/employees_data.html', {"employees": employees})


def employee_details(request, slug):
    employee = Employee.objects.get(slug=slug)
    return render(request, 'employees/employee_details.html', {"employee": employee})

my_project/templates/employees/employee_details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>&nbsp;employee-details </title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head><h1></h1>
<body>
<div class="home-page" ><a href="{% url 'employees:data' %}" ><img src="{% static 'back.png' %}" style="width:60px; height:60px;"></a></div>
  <div class="employee-details">
    <h1><img class="emp-img" src="{{ employee.thumb.url }}" style="width:200px; height:220px;">{{ employee.first_name }}&nbsp{{ employee.last_name }}&nbsp
        {{ employee.job_id }}</h1>
     <div class="general"><h3>{{ employee.general }}</h3></div>
  </div>


</body>
</html>

my_project/templates/employees/employees_data.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Employees</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<h2>Employees data</h2>

    <div class="employee">
        <table class="workers-table">
            <tr>
                <th>Employee ID</th>
                <th>First name</th>
                <th>Last name</th>
                <th>email</th>
                <th>Phone number</th>
                <th>Hire date</th>
                <th>Job ID</th>
                <th>Salary</th>
                <th>Manager ID</th>
                <th>Department ID</th>
            </tr>
            <tr>
                {% for employee in employees %}
                <td>{{ employee.employee_id }}</td>
                <td><a href="{% url 'employees:details' slug=employee.slug %}">{{ employee.first_name }}</a></td>
                <td>{{ employee.last_name }}</td>
                <td>{{ employee.email }}</td>
                <td>{{ employee.phone_number }}</td>
                <td>{{ employee.hire_date }}</td>
                <td>{{ employee.job_id }}</td>
                <td>{{ employee.salary }}</td>
                <td>{{ employee.manager_id }}</td>
                <td>{{ employee.department_id }}</td>
            </tr>
                {% endfor %}

           <a href="http://127.0.0.1:8000/my_app/api/" target="_blank" class="api-link"><h3>go to rest api</h3></a>

        </table>

    </div>

</body>
</html>